# Artist.create({name:"Michael Jackson", solo:true, genre:"Pop"})
# Artist.create({name:"Maroon 5", solo:false, genre:"Pop"})
# Artist.create({name:"Lifehouse", solo:false, genre:"rock"})
# Artist.create({name:"Chris Tomlin", solo:true, genre:"Christian"})
# Artist.create({name:"Fela", solo:true, genre:"Afro-Beat"})

Song.create({artist_id:1, title:"Billie Jean"})
Song.create({artist_id:1, title:"You Rock My World"})
Song.create({artist_id:2, title:"Move Like Jaeger"})
Song.create({artist_id:3, title:"You and Me"})
Song.create({artist_id:4, title:"Waterfall"})
Song.create({artist_id:4, title:"Lay me Down"})
Song.create({artist_id:5, title:"Shuffering and Shmiling"})